apiVersion: v1
kind: Namespace
metadata:
  name: tarea-01

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: tarea-01
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:14
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: roberth
            - name: POSTGRES_PASSWORD
              value: password
            - name: POSTGRES_DB
              value: GestionUsuarios
          volumeMounts:
            - name: init-scripts
              mountPath: /docker-entrypoint-initdb.d
              readOnly: true
      volumes:
        - name: init-scripts
          configMap:
            name: init-scripts-config
