apiVersion: v1
kind: Namespace
metadata:
  name: tarea-01
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: tarea-01
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: miltonrcr/backend:latest
          ports:
            - containerPort: 4000
          env:
            - name: DB_HOST
              value: postgres
            - name: DB_PORT
              value: "5432"
            - name: DB_USER
              value: roberth
            - name: DB_PASSWORD
              value: password
            - name: DB_NAME
              value: GestionUsuarios
---
kind: Service
apiVersion: v1
metadata:
  name: backend
  namespace: tarea-01
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 4000
      targetPort: 4000
  type: ClusterIP
