# Namespace
apiVersion: v1
kind: Namespace
metadata:
  name: tarea-01

---

# Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: tarea-01
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: miltonrcr/frontend:latest
        ports:
        - containerPort: 3001
        resources:
          requests: 
            memory: "128Mi"
            cpu: "250m"
          limits:
            memory: "256Mi"
            cpu: "500m"

---

# Service (LoadBalancer)
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: tarea-01
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3001
  type: LoadBalancer
